{% set name = "pyart_mch" %}
{% set version = "2.0.0" %}
{% set sha256 = "3a9deab23d56f9d898060ebf20012909dc92ec81dd1a7fed055ce3cc0fb1bd45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - export RSL_PATH=$PREFIX    # [not win]
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cython
host:
    - python
    - pip
    - numpy >=1.18
    - cython >=0.24.0,<3.0.10
    - setuptools_scm
  run:
    - python
    - setuptools
    - setuptools_scm
    - numpy >=1.18
    - scipy
    - matplotlib-base
    - netcdf4
    - xarray
    - pooch
    - versioneer
    - fsspec
    - s3fs
    - cftime
    - xradar >=0.5.0
    - open-radar-data
    - pandas
    - mda-xdrlib

test:
  imports:
    - pyart

about:
  home: https://github.com/MeteoSwiss/pyart
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MeteoSwiss version of Py-ART, the Python ARM Radar Toolkit
  description: |
    This is the MeteoSwiss version of Py-ART. Py-ART, is an open source Python
    module containing a growing collection of weather radar algorithms
    and utilities build on top of the Scientific Python stack and
    distributed under the 3-Clause BSD license. Py-ART is used by the
    Atmospheric Radiation Measurement (ARM) Climate Research Facility for
    working with data from a number of precipitation and cloud radars, but
    has been designed so that it can be used by others in the radar and
    atmospheric communities to examine, process, and analyze data from many
    types of weather radars. The MeteoSwiss version contains enhanced
    and experimental functionality. MeteoSwiss regularly contributes back to
    the ARM-DOE Py-ART.
  doc_url: https://pyart-mch.readthedocs.io/en/stable/
  dev_url: https://github.com/MeteoSwiss/pyart

extra:
  recipe-maintainers:
    - meteoswiss-mdr
